dist: trusty
language: node_js
node_js:
- stable
script:
- npm run coverage
after_success:
- npm run publish-coverage
branches:
  only: development
notifications:
  email:
    recipients:
    - ywjg_99@126.com
    on_success: never
    on_failure: always
